pipeline {
    agent any
    environment {
                frontendRegistry = 'docker.pkg.github.com/zemoso-int/devops-bootcamp-3/book-discovery-frontend'
                backendRegistry = 'docker.pkg.github.com/zemoso-int/devops-bootcamp-3/book-discovery-backend'
                registryCredential = 'github-registry'
                GH_TOKEN = credentials('GHB_TOKEN')
                dockerImage = ''
    }
    stages {
        stage('Build backend') {
            steps {
                checkout scm
                sh 'pwd'
                sh 'cd book-discovery-app/bc-5-backend/book-management-service && mvn -B -DskipTests clean package'
            }
        }
        stage('Testing backend') {
            steps {
                sh 'pwd'
                sh 'cd book-discovery-app/bc-5-backend/book-management-service && mvn test'
            }
        }
        stage('Building Docker Image for backend') {
            steps {
                dir('book-discovery-app/bc-5-backend/book-management-service') {
                    script {
                        dockerImage = docker.build backendRegistry + ":$BUILD_NUMBER"
                    }
                }
            }
        }
        stage('Deploy Docker Image for backend') {
            steps {
                sh 'docker login docker.pkg.github.com -u Md-Khaleelur -p ${GH_TOKEN}'
                sh 'docker push ' + backendRegistry + ":$BUILD_NUMBER"
            }
        }
        stage('Build frontend') {
                    steps {
                        sh 'pwd'
                        sh 'cd book-discovery-app/bc-5-frontend && rm -rf node_modules/ && npm install'
                    }
        }
        stage('Testing frontend') {
                    steps {
                        sh 'pwd'
                        sh 'cd book-discovery-app/bc-5-frontend && npm run test'
                    }
        }
        stage('Building Docker Image for frontend') {
            steps {
                dir('book-discovery-app/bc-5-frontend') {
                    script {
                        dockerImage = docker.build frontendRegistry + ":$BUILD_NUMBER"
                    }
                }
            }
        }
        stage('Deploy Docker Image for frontend') {
            steps {
                sh 'docker login docker.pkg.github.com -u Md-Khaleelur -p ${GH_TOKEN}'
                sh 'docker push ' + frontendRegistry + ":$BUILD_NUMBER"
            }
        }

    }
}
