pipeline {
    agent any
    environment {
                frontendRegistry = 'docker.pkg.github.com/zemoso-int/devops-bootcamp-3/book-discovery-frontend'
                backendRegistry = 'docker.pkg.github.com/zemoso-int/devops-bootcamp-3/book-discovery-backend'
                registryCredential = 'github-registry'
                GH_TOKEN = credentials('GHB_TOKEN')
                dockerImage = ''
    }
    stages {
        stage('Build backend') {
            steps {
                checkout scm
                sh 'pwd'
                sh 'cd book-discovery-app/bc-5-backend/book-management-service && mvn -B -DskipTests clean package'
            }
        }
        stage('Testing backend') {
            steps {
                sh 'pwd'
                sh 'cd book-discovery-app/bc-5-backend/book-management-service && mvn test'
            }
        }
        stage('Building Docker Image for backend') {
            steps {
                dir('book-discovery-app/bc-5-backend/book-management-service') {

                 sh "docker build . -t "+backendRegistry+"book-discovery-backend:$BUILD_NUMBER -t "+backendRegistry+"book-discovery-backend:latest"

                }
            }
        }
        stage('Deploy Docker Image for backend') {
            steps {
				sh 'echo ${GH_TOKEN} | docker login docker.pkg.github.com -u Md-Khaleelur --password-stdin'
                sh 'docker push ' + backendRegistry + "book-discovery-frontend:$BUILD_NUMBER"
                sh 'docker push ' + backendRegistry + "book-discovery-backend:latest"
            }
        }
        stage('Build frontend') {
                    steps {
                        sh 'pwd'
                        sh 'cd book-discovery-app/bc-5-frontend && rm -rf node_modules/ && npm install'
                    }
        }
        stage('Testing frontend') {
                    steps {
                        sh 'pwd'
                        sh 'cd book-discovery-app/bc-5-frontend && npm run test'
                    }
        }
        stage('Building Docker Image for frontend') {
            steps {
                dir('book-discovery-app/bc-5-frontend') {

                        sh "docker build . -t "+frontendRegistry+"book-discovery-frontend:$BUILD_NUMBER -t "+frontendRegistry+"book-discovery-frontend:latest"

                }
            }
        }
        stage('Deploy Docker Image for frontend') {
            steps {
				sh 'echo ${GH_TOKEN} | docker login docker.pkg.github.com -u Md-Khaleelur --password-stdin'
                sh 'docker push ' + frontendRegistry + "book-discovery-frontend:$BUILD_NUMBER"
                sh 'docker push ' + frontendRegistry + "book-discovery-frontend:latest"
            }
        }

    }
}
